apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: satelite-sensor-deployment
  namespace: default
  labels:
    app: satelite-sensor-deployment
spec:
  replicas: 1 # number of pods
  selector:
    matchLabels:
      app: satelite-sensor-deployment
  template:
    metadata:
      labels:
        app: satelite-sensor-deployment
    spec:
      containers:
        - name: satelite-sensor-image
          image: IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP