apiVersion: apps/v1
kind: Deployment
metadata:
  name: satelite-sensor-deployment-5
  namespace: default
  labels:
    app: satelite-sensor-deployment-5
spec:
  replicas: 1 # number of pods
  selector:
    matchLabels:
      app: satelite-sensor-deployment-5
  template:
    metadata:
      labels:
        app: satelite-sensor-deployment-5
    spec:
      containers:
        - name: satelite-sensor-image-5
          image: IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP