apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: satelite-sensor-ingress-4
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "satelite-sensor-ip"
spec:
  backend:
    serviceName: satelite-sensor-deployment-4
    servicePort: 3000