apiVersion: v1
kind: Service
metadata:
  name: satelite-sensor-deployment
spec:
clusterIP: 100.0.0.3
  selector:
    app: satelite-sensor-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000