# apiVersion: v1
# kind: Service
# metadata:
#   name: satelite-sensor-service
# spec:
#   selector:
#     app: satelite-sensor-deployment
#   type: LoadBalancer
#   ports:
#     - protocol: TCP
#       port: 3000
#       targetPort: 3000