apiVersion: v1
kind: Service
metadata:
  name: satelite-sensor-deployment-5
spec:
  selector:
    app: satelite-sensor-deployment-5
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000