apiVersion: v1
kind: Service
metadata:
  name: satelite-sensor-deployment
spec:
  type: ClusterIP
  selector:
    app: satelite-sensor-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000